format_version = 2
map_id = "test_map_2"
width = 1250
height = 1250
spacing_m = 4.0
vert_min_m = 0.0
vert_max_m = 131.39797973632813
origin_utm_zone = "10N"
origin_utm_easting = 0.0
origin_utm_northing = 0.0
blake3 = "23ac6cbc2e6e823ad8131868831f35859ef083ef74d00fb55142626bb4d8ec11"
features_blake3 = ""
region_size_m = 2048.0
playable_extent_x_m = 0.0
playable_extent_z_m = 0.0
nav_mask_format_version = 0
nav_mask_blake3 = ""
